database:
  file_path: data/db/personal_finance_app.db

user_interface:
  drop_down_options:
    - "Spending: Needs"
    - "Spending: Wants"
    - "Spending: Investments"
    - "Income"

application_settings:
  budget_breakdown:
    Needs: 0.50
    Wants: 0.30
    Investments: 0.20